language: r
sudo: required

before_install:
- echo "options(repos = c(CRAN='https://cran.rstudio.com/'))" > ~/.Rprofile
r_github_packages:
  - rstudio/rmarkdown
  - hadley/testthat
  - jimhester/covr
  - jimhester/lintr

bioc_packages:
  - BiocInstaller

after_success:
  script: ./upload.R



env:
  global:
    secure: se9MhsWZ8xZ3ukpCnxsU