language: r
sudo: required

r_github_packages:
 - rstudio/shiny

script:
Rscript -e 'library(shinyapps);setAccountInfo(name='agile2015',
                         token='9473BA7423C35A47B97AD199108456AD',
                  secret='1jAXKNKweZ38GKPeKvJY9d/R55AGTlu6FEzC6XJZ');deployApp('./src/DeployR')'

env:
  global:
    secure: se9MhsWZ8xZ3ukpCnxsU